# Generated by Django 5.2.6 on 2025-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_encrypted', models.BinaryField()),
                ('email_encrypted', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
