# Generated by Django 5.2.6 on 2025-09-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email_encrypted',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='name_encrypted',
        ),
        migrations.AddField(
            model_name='userdata',
            name='_email',
            field=models.TextField(db_column='email', default='temp_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='_name',
            field=models.TextField(db_column='name', default='temp_name'),
            preserve_default=False,
        ),
    ]
