# Generated by Django 5.2.6 on 2025-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdata_email_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='_email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='encrypted_email',
            field=models.TextField(default='temp_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='encrypted_name',
            field=models.TextField(default='temp_name'),
            preserve_default=False,
        ),
    ]
