# Generated by Django 5.2.6 on 2025-09-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userdata__email_remove_userdata__name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='encrypted_email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='encrypted_name',
            new_name='_name',
        ),
    ]
